# 1. Import and Install Dependencies

# Run installs

In [4]:
!pip install mediapipe
!pip install tensorflow==2.14.0
!pip install opencv-python
!pip install mediapipe
!pip install matplotlib

# Run preps

In [23]:
import cv2
import numpy as np
import os
from matplotlib import pyplot as plt
import time
import mediapipe as mp
from tensorflow import keras
import tensorflow
from sklearn.metrics import multilabel_confusion_matrix, accuracy_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.callbacks import TensorBoard
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

mp_holistic = mp.solutions.holistic # Holistic model
mp_drawing = mp.solutions.drawing_utils # Drawing utilities

def mediapipe_detection(image, model):
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) # COLOR CONVERSION BGR 2 RGB
    image.flags.writeable = False                  # Image is no longer writeable
    results = model.process(image)                 # Make prediction
    image.flags.writeable = True                   # Image is now writeable 
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR) # COLOR COVERSION RGB 2 BGR
    return image, results

def draw_landmarks(image, results):
    mp_drawing.draw_landmarks(image, results.face_landmarks, mp_holistic.FACEMESH_CONTOURS) # Draw face connections
    mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS) # Draw pose connections
    mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS) # Draw left hand connections
    mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS) # Draw right hand connections

def draw_styled_landmarks(image, results):
    # Draw face connections
    mp_drawing.draw_landmarks(image, results.face_landmarks, mp_holistic.FACEMESH_CONTOURS, 
                             mp_drawing.DrawingSpec(color=(80,110,10), thickness=1, circle_radius=1), 
                             mp_drawing.DrawingSpec(color=(80,256,121), thickness=1, circle_radius=1)
                             ) 
    # Draw pose connections
    mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS,
                             mp_drawing.DrawingSpec(color=(80,22,10), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(80,44,121), thickness=2, circle_radius=2)
                             ) 
    # Draw left hand connections
    mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                             mp_drawing.DrawingSpec(color=(121,22,76), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(121,44,250), thickness=2, circle_radius=2)
                             ) 
    # Draw right hand connections  
    mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                             mp_drawing.DrawingSpec(color=(245,117,66), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(245,66,230), thickness=2, circle_radius=2)
                             )
    
def extract_keypoints(results):
    pose = np.array([[res.x, res.y, res.z, res.visibility] for res in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks else np.zeros(33*4)
    face = np.array([[res.x, res.y, res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(468*3)
    lh = np.array([[res.x, res.y, res.z] for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21*3)
    rh = np.array([[res.x, res.y, res.z] for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*3)
    return np.concatenate([pose, lh, rh])

def rename_dirs(starting_pos):
    all_data_dir_path = os.path.join(os.getcwd(), 'MP_Data')
    
    activities_dirs = [name for name in os.listdir(all_data_dir_path) if os.path.isdir(os.path.join(all_data_dir_path, name))]
    
    if not len(activities_dirs):
        return
    
    # Get the current directory
    for activity_dir_name in activities_dirs:
        banned_names = ["move_left", "move_right", "pc_lock", "pc_on"]
        if activity_dir_name in banned_names:
            continue
        activity_dir_path = os.path.join(all_data_dir_path, activity_dir_name)
    
        # List all directories in the current location
        activity_dir_enumerated_dirs = [num_name for num_name in os.listdir(activity_dir_path) if os.path.isdir(os.path.join(activity_dir_path, num_name))]

    
        if starting_pos > 0:
            activity_dir_enumerated_dirs.sort(reverse=True, key=int)
        else:
            activity_dir_enumerated_dirs.sort(reverse=False, key=int)

        # Rename the directories
        for directory_num_name in activity_dir_enumerated_dirs:
            new_name = int(directory_num_name) + int(starting_pos)
            os.rename(os.path.join(activity_dir_path, str(directory_num_name)), os.path.join(activity_dir_path, str(new_name)))

def prob_viz(res, actions, input_frame, colors):
    output_frame = input_frame.copy()
    for num, prob in enumerate(res):
        cv2.rectangle(output_frame, (0,60+num*40), (int(prob*100), 90+num*40), colors[num], -1)
        cv2.putText(output_frame, actions[num], (0, 85+num*40), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,255,255), 2, cv2.LINE_AA)
        
    return output_frame

colors = [(245,117,16), (117,245,16), (16,117,245), (1,100,200), (10,50,70), (1,150,30)]

# Path for exported data, numpy arrays
DATA_PATH = os.path.join('MP_Data') 

# Actions that we try to detect
# actions = np.array(['pc_on', 'pc_lock', 'move_left', 'move_right', 'show_desktop', 'mute'])
actions = np.array(['pc_on', 'pc_lock', 'move_left', 'move_right', 'show_desktop', 'mute'])

# Thirty videos worth of data
no_sequences = 30

# Videos are going to be 30 frames in length
sequence_length = 30

# Run test keypoints

In [2]:
cap = cv2.VideoCapture(0)
# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():

        # Read feed
        ret, frame = cap.read()

        # Make detections
        image, results = mediapipe_detection(frame, holistic)
        print(results)
        
        # Draw landmarks
        draw_styled_landmarks(image, results)

        # Show to screen
        cv2.imshow('OpenCV Feed', image)

        # Break gracefully
        if cv2.waitKey(10) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()

<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.soluti

# Manage folders

In [5]:
for action in actions: 
    for sequence in range(no_sequences):
        try: 
            os.makedirs(os.path.join(DATA_PATH, action, str(sequence)))
        except:
            pass

In [45]:
rename_dirs(0)

# Collect Keypoint Data for Training

In [6]:
cap = cv2.VideoCapture(0)
# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    
    # NEW LOOP
    # Loop through actions
    for action in actions:
        # Loop through sequences aka videos
        for sequence in range(no_sequences):
            # Loop through video length aka sequence length
            for frame_num in range(sequence_length):

                # Read feed
                ret, frame = cap.read()

                # Make detections
                image, results = mediapipe_detection(frame, holistic)
#                 print(results)

                # Draw landmarks
                draw_styled_landmarks(image, results)
                
                # NEW Apply wait logic
                if frame_num == 0: 
                    cv2.putText(image, 'STARTING COLLECTION', (120,200), 
                               cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255, 0), 4, cv2.LINE_AA)
                    cv2.putText(image, 'Collecting frames for {} Video Number {}'.format(action, sequence), (15,12), 
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    # Show to screen
                    cv2.imshow('OpenCV Feed', image)
                    cv2.waitKey(700)
                else: 
                    cv2.putText(image, 'Collecting frames for {} Video Number {}'.format(action, sequence), (15,12), 
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    # Show to screen
                    cv2.imshow('OpenCV Feed', image)
                
                # NEW Export keypoints
                keypoints = extract_keypoints(results)
                npy_path = os.path.join(DATA_PATH, action, str(sequence), str(frame_num))
                np.save(npy_path, keypoints)

                # Break gracefully
                if cv2.waitKey(10) & 0xFF == ord('q'):
                    break
                    
    cap.release()
    cv2.destroyAllWindows()

In [8]:
cap.release()
cv2.destroyAllWindows()

# Build and Train LSTM Neural Network

In [12]:
label_map = {label:num for num, label in enumerate(actions)}
sequences, labels = [], []

# Define the number of sequences for each action
no_sequences_per_action = {
    'pc_on': 30,
    'pc_lock': 30,
    'move_left': 30,
    'move_right': 30,
    'show_destkop': 30,
    'mute': 30
}

for action in actions:
    no_sequences = no_sequences_per_action.get(action, 30)  # Default to 30 sequences if not specified
    
    for sequence in range(no_sequences):
        window = []
        for frame_num in range(sequence_length):
            res = np.load(os.path.join(DATA_PATH, action, str(sequence), "{}.npy".format(frame_num)))
            window.append(res)
        sequences.append(window)
        labels.append(label_map[action])

np.save('sequences.npy', np.array(sequences, dtype=object), allow_pickle=True)
np.save('labels.npy', np.array(labels, dtype=object), allow_pickle=True)

y = to_categorical(labels).astype(int)
X = np.array(sequences)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05)

log_dir = os.path.join('Logs')
tb_callback = TensorBoard(log_dir=log_dir)
model = Sequential()
model.add(LSTM(64, return_sequences=True, activation='relu', input_shape=(30, 258), name='lstm_1'))
model.add(LSTM(128, return_sequences=True, activation='relu', name='lstm_2'))
model.add(LSTM(64, return_sequences=False, activation='relu', name='lstm_3'))
model.add(Dense(64, activation='relu', name='dense_1'))
model.add(Dense(32, activation='relu', name='dense_2'))
model.add(Dense(actions.shape[0], activation='softmax', name='output_layer'))
res = [.7, 0.2, 0.1]
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

In [13]:
np.array(sequences).shape

(180, 30, 258)

In [22]:
actions.shape[0]

6

In [14]:
model.fit(X_train, y_train, epochs=500, callbacks=[tb_callback])

Epoch 1/500
6/6 [==============================] - 5s 37ms/step - loss: 1.6537 - categorical_accuracy: 0.2807
Epoch 2/500
6/6 [==============================] - 0s 35ms/step - loss: 1.1767 - categorical_accuracy: 0.6199
Epoch 3/500
6/6 [==============================] - 0s 43ms/step - loss: 0.9239 - categorical_accuracy: 0.6316
Epoch 4/500
6/6 [==============================] - 0s 36ms/step - loss: 0.7512 - categorical_accuracy: 0.6316
Epoch 5/500
6/6 [==============================] - 0s 37ms/step - loss: 0.8104 - categorical_accuracy: 0.6550
Epoch 6/500
6/6 [==============================] - 0s 37ms/step - loss: 0.4514 - categorical_accuracy: 0.8070
Epoch 7/500
6/6 [==============================] - 0s 34ms/step - loss: 0.8342 - categorical_accuracy: 0.7836
Epoch 8/500
6/6 [==============================] - 0s 35ms/step - loss: 0.5016 - categorical_accuracy: 0.7018
Epoch 9/500
6/6 [==============================] - 0s 33ms/step - loss: 0.4257 - categorical_accuracy: 0.7895
Epoch 10/5

# Save/Load model 

In [15]:
model.save('my_model.keras')

model.load('my_model.keras')

In [24]:
model = keras.models.load_model('150rc4fun.keras')

# Test in Real Time

In [25]:
# 1. New detection variables
sequence = []
sentence = []
threshold = 0.95

cap = cv2.VideoCapture(0)
# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():

        # Read feed
        ret, frame = cap.read()

        # Make detections
        image, results = mediapipe_detection(frame, holistic)
        #print(results)
        
        # Draw landmarks
        draw_styled_landmarks(image, results)
        
        # 2. Prediction logic
        keypoints = extract_keypoints(results)
#         sequence.insert(0,keypoints)
#         sequence = sequence[:30]
        sequence.append(keypoints)
        sequence = sequence[-30:]
        
        if len(sequence) == 30:
            res = model.predict(np.expand_dims(sequence, axis=0))[0]
            print(res)
            #print(actions[np.argmax(res)])
            
            # Calculate recognition percentage
            recognition_percentage = round(100 * res[np.argmax(res)], 2)
            print(f"Gesture recognition percentage: {recognition_percentage}%")
            
        #3. Viz logic
            if res[np.argmax(res)] > threshold: 
                if len(sentence) > 0: 
                    if actions[np.argmax(res)] != sentence[-1]:
                        sentence.append(actions[np.argmax(res)])
                else:
                    sentence.append(actions[np.argmax(res)])

            if len(sentence) > 5: 
                sentence = sentence[-5:]

            # Viz probabilities
            #print(res)
            #print(colors)
            image = prob_viz(res, actions, image, colors)
            
        cv2.rectangle(image, (0,0), (640, 40), (245, 117, 16), -1)
        cv2.putText(image, ' '.join(sentence), (3,30), 
                       cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)
        
        # Show to screen
        cv2.imshow('OpenCV Feed', image)

        # Break gracefully
        if cv2.waitKey(10) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()


1/1 [==============================] - 0s 406ms/step
[1.3842062e-07 5.3512954e-09 9.9999988e-01 5.6617705e-10]
Gesture recognition percentage: 100.0%
1/1 [==============================] - 0s 25ms/step
[1.6925654e-07 6.7900983e-09 9.9999988e-01 7.2899065e-10]
Gesture recognition percentage: 100.0%
1/1 [==============================] - 0s 26ms/step
[3.0887531e-07 9.8038839e-09 9.9999964e-01 1.2158101e-09]
Gesture recognition percentage: 100.0%
1/1 [==============================] - 0s 24ms/step
[1.0573481e-06 2.4708697e-08 9.9999893e-01 3.6103613e-09]
Gesture recognition percentage: 100.0%
1/1 [==============================] - 0s 24ms/step
[5.4331399e-06 1.1870157e-07 9.9999440e-01 1.6847478e-08]
Gesture recognition percentage: 100.0%
1/1 [==============================] - 0s 24ms/step
[3.1199332e-05 5.9849179e-07 9.9996805e-01 7.0894714e-08]
Gesture recognition percentage: 100.0%
1/1 [==============================] - 0s 25ms/step
[1.8854598e-04 2.5809422e-06 9.9980861e-01 2.7783466e